name = "gasah"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
build_output_directory = ".next"

[env.production]
NEXT_PUBLIC_APP_URL = "https://gasah.pages.dev"
NODE_ENV = "production"