name = "sahl-system"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "sahl-database"
database_id = "sahl-database"

# Environment variables
[env.production]
vars = { NODE_ENV = "production" }

# Build configuration for Pages
[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "out"
main = "./functions/api/[[catchall]].js"

# Site configuration
[site]
bucket = "./out"